package medicaldoctor.core;

public enum Permission {
    REGISTER_NEW_USER,
    REGISTER_PATIENT,
    VIEW_HEMOTOLOGIC_BUTTONS,
    VIEW_RADIOLOGIC_BUTTONS,
    ACCESS_PATIENT_LOOKUP,
    ACCESS_DOCTOR_LOOKUP,
    ACCESS_USER_LOOKUP,
    ACCESS_MY_PATIENTS,
    ACCESS_MY_LAB_REQUESTS,
    ACCESS_ALL_LAB_REQUESTS,
    ACCESS_ALL_LAB_PATIENTS,
    ACCESS_LOGS,
    EDIT_PATIENT_VISIT
}
